feat: implement new node matcher API
quarylabs/sqruff pull request #370
Opened 2024-06-15 17:22 UTC by gvozdvmozgu

2024-06-26 15:05 UTC, gvozdvmozgu commented
For this, we need a separate counter. We also have a problem where the `cache_key` is created for each instance, but currently, we don't store the instances; they are created and immediately dropped. This is about grammar, and it is resolved in [this pull request](https://github.com/quarylabs/sqruff/pull/370).

2024-06-27 18:32 UTC, gvozdvmozgu commented
Oh, I wanted to comment on a different PR

2024-06-30 10:27 UTC, benfdking requested changes
Amazing work! I think there's one TODO that we can clean up? If not let me know.

2024-06-30 10:27 UTC, benfdking commented on crates/lib/src/core/parser/segments/base.rs
> +        // TODO: remove hack
I think this can be removed?

2024-06-30 12:17 UTC, benfdking approved these changes

2024-06-30 12:17 UTC, merged